name: LANDMark

dependencies:
    - python >=3.11
    - pip
    - pip:
        - numpy == 2.1.3
        - scikit-learn >= 1.6.1
        - joblib >= 1.4.2
        - pandas >= 2.2.3
        - scipy >= 1.15.2
        - torch >= 2.6.0
